[build]
  command = "" # 빌드 프로세스가 없으므로 빈 값으로 설정
  publish = "." # 현재 디렉터리를 배포 디렉터리로 설정
  functions = "netlify/functions" # Netlify 함수 디렉터리 설정

[build.environment]
  NODE_VERSION = "18.20.0" # 로컬에서 사용하는 Node.js 버전

[context.production.environment]
  # 프로덕션 환경에서의 환경 변수를 설정할 수 있습니다.
  OPENAI_API_KEY = "your-api-key-here"