[build]
  # 빌드 명령어를 지정할 수 있습니다.
  command = "npm run build"

[build.environment]
  # 사용하려는 Node.js 버전을 명시합니다.
  NODE_VERSION = "16"

[context.production.environment]
  # 프로덕션 환경에서의 환경 변수를 설정할 수 있습니다.
  OPENAI_API_KEY = "your-api-key-here"
