[build]
command = "npm install && npm run build"
publish = "dist"
functions = "netlify/functions"


[build.environment]
NODE_VERSION = "18.20.0" # 로컬에서 사용하는 Node.js 버전

[context.production.environment]
  # 프로덕션 환경에서의 환경 변수를 설정할 수 있습니다.
  OPENAI_API_KEY = "your-api-key-here"